### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by daybarr**
Hi again @pokidovea .

I have rewritten the core of the README to give a walk-through of the major features [as requested](https://github.com/pokidovea/immobilus/pull/19#issuecomment-337659470). It's a big change to it, I hope you like it.

I've done the examples in a doctest style which means that they can actually be tested by the tests. This is quite useful and means that this public document of the API should not be broken by changes to immobilus, and any trivial typos I might have written (#16? :wink:) would also have resulted in broken tests.

### CODE REVIEW

**Comment by pokidovea** [comment]
Excellent job. I'm very grateful to you! A new version will be published soon.

**Comment by pokidovea** [comment]
Meet a new version of [immobilus](https://pypi.python.org/pypi/immobilus/1.0)

**Comment by daybarr** [comment]
Thanks for the shiny 1.0 release :smile: 

I thought you might like to see this. For our usage on a non-trivial Django project, we could replace freezegun with immobilus like so

```bash
find -type f -name '*.py' -exec sed -i -e 's/freezegun/immobilus/g' -e 's/freeze_time/immobilus/g' "{}" \;
```

(we are not using advanced features of freezegun like "tick", so for us, the API is compatible and immobilus is a "drop in" replacement now)

When I run the tests before and after:

Lib | Elapsed time to run 1409 tests
------------ | -------------
freezegun |  14m59.201s
immobilus | 5m35.825s

💃 

We have a happy team here. Would not be possible without what you'd built. Thanks again.

**Comment by pokidovea** [comment]
Thanks for your help, friend! I'm glad to see that my tool is useful to you.

**Pull request merged**
