### PR TITLE
Problems when freezing with an offset-aware datetime

### PR DESCRIPTION
**Pull request by daybarr**
```
>>> import datetime, time
>>> import immobilus, pytz
>>>
>>> with immobilus.immobilus(datetime.datetime(2017, 1, 1, tzinfo=pytz.utc)):
...     time.time()
...
Traceback (most recent call last):
  File "<console>", line 2, in <module>
  File "c:\users\day.barr\dev\immobilus\immobilus\logic.py", line 56, in fake_time
    return _datetime_to_utc_timestamp(TIME_TO_FREEZE)
  File "c:\users\day.barr\dev\immobilus\immobilus\logic.py", line 49, in _datetime_to_utc_timestamp
    delta = dt - original_datetime(1970, 1, 1)
  File "c:\users\day.barr\dev\immobilus\immobilus\logic.py", line 160, in __sub__
    result = datetime.__sub__(self, other)
TypeError: can't subtract offset-naive and offset-aware datetimes
```

First 2 commits create a failing test like the above.

Then a targeted fix in the next commit.

Then... maybe I want too far trying to refactor a little? I thought that the code in `logic.py` could be simplified by converting `TIME_TO_FREEZE`  into a naive UTC time just once, when `immobilus.start` is called. Then all the `if TIME_TO_FREEZE.tzinfo` calculations in the various `fake_*` methods can go away - `TIME_TO_FREEZE.tzinfo` will always be `None`, because we converted it to be naive.

This does mean that the behaviour you have in [`FakeDatetime.fromtimestamp`](https://github.com/pokidovea/immobilus/blob/39a0daf08fe6cd43ddf3ab71c17a4f7f20c7ef8e/immobilus/logic.py#L210) to use the timezeone from `TIME_TO_FREEZE`, as tested in [`test_fromtimestamp_takes_tz_from_frozen_datetime`](https://github.com/pokidovea/immobilus/blob/39a0daf08fe6cd43ddf3ab71c17a4f7f20c7ef8e/tests/test_datetime.py#L175-L182) no longer works. Is that really desirable? As far as I can see, this is the only place that really uses `TIME_TO_FREEZE.tzinfo` to affect the result of the function. If we're going to use anything here to fake the "local time", shouldn't it be the `TZ_OFFSET` instead which is intended for exactly that?

I've tried to do that, then fix the resulting knock-on effects this had on some other tests. I *think* the result makes sense to me, although I am quite tired now and must get some sleep ;)

Please let me know if the above (and my changes here) make sense to you, or if I have misunderstood. Thanks.

### CODE REVIEW

**Comment by pokidovea** [comment]
Oh, those timezones...I need some time.

**Comment by pokidovea** [comment]
I don't know, why tests pass on travis, but change `calendar.timegm(timetuple)` to `original_mktime(timetuple)` in fake_mktime is wrong. The `original_mktime` has a side effect: it uses the time in local time, not UTC as argument while `calendar.timegm` accepts a utc time.
Locally I have 3 failing tests:
```
__________________________________________________________________________________ test_transmutations __________________________________________________________________________________

    def test_transmutations():
        with immobilus('2017-01-01 00:00:00', tz_offset=2):
            now = datetime.now()
            timetuple = now.timetuple()
            mktime = time.mktime(timetuple)
            fromtimestamp = datetime.fromtimestamp(mktime)
    
>           assert now.replace(microsecond=0) == fromtimestamp
E           assert FakeDatetime(2017, 1, 1, 2, 0) == datetime.datetime(2016, 12, 31, 23, 0)
E            +  where FakeDatetime(2017, 1, 1, 2, 0) = <built-in method replace of FakeDatetime object at 0x7fd254f0d410>(microsecond=0)
E            +    where <built-in method replace of FakeDatetime object at 0x7fd254f0d410> = FakeDatetime(2017, 1, 1, 2, 0).replace

tests/test_general.py:14: AssertionError
_____________________________________________________________________________ test_mktime_without_timezone ______________________________________________________________________________

    def test_mktime_without_timezone():
        with immobilus('1970-01-01 00:00:00'):
            timestamp = _datetime_to_utc_timestamp(datetime.utcnow())
    
            timetuple = datetime.utcnow().timetuple()
            mktime = time.mktime(timetuple)
    
>           assert mktime == timestamp
E           assert -10800.0 == 0.0

tests/test_mktime.py:16: AssertionError
_______________________________________________________________________ test_mktime_gets_timezone_from_timetuple ________________________________________________________________________

    def test_mktime_gets_timezone_from_timetuple():
        timezone = pytz.timezone('US/Eastern')
        dt = timezone.localize(datetime(1970, 1, 1, 0, 0))
    
        with immobilus(dt):
            import pdb; pdb.set_trace()
            timestamp = _datetime_to_utc_timestamp(datetime.utcnow())
    
            timetuple = datetime.utcnow().timetuple()
>           mktime = time.mktime(timetuple)
E           assert 7200.0 == 18000.0

tests/test_mktime.py:28: AssertionError
```
But when I change to `calendar.timegm` they pass.

Sorry for my english, if something wrong.

**Comment by pokidovea** [comment]
Possibly timezone on travis is UTC

**Comment by pokidovea** [comment]
Ping

**Comment by daybarr** [comment]
Sorry @pokidovea I've been too busy with other things to get back to you :(

It looks like I did go too far in refactoring. Perhaps, for now, you could take just the commits up to (and including) 72ab620? That would solve the problem reported in the PR description, without including the further changes I made to `mktime` etc that are causing the issues you report above?

I'll have a proper think about the `mktime` / `fromtimestamp` issues when I get time soon.

I am having trouble understanding what "local time" means when immobilus is active. As I understand it, we have to write the fake functions so that they completely ignore the actual system timezone that is in effect. Instead, for "local time" the fake functions should apply the `TZ_OFFSET` to the UTC time given by `TIME_TO_FREEZE`. This means that we never use the timezone that is applied to `TIME_TO_FREEZE` (if `TIME_TO_FREEZE` is given to us with a timezone, we just use that timezone to convert it to a naive UTC time). I probably just need to work through more tests to be sure I understand this.

By the way, your English is excellent. I hope you can understand mine ;)

**Comment by pokidovea** [comment]
I like your idea. I'll merge and adjust your PR. But, I want to ask you as a native speaker to help me with doc. We need to reflect this behavior in the documentation. Main points:

- anything, that passed to immobilus as time_to_freeze will be converted to UTC naive
- if you want local time to differ from utc - set tz_offset

I think, it would be a new major version!

**Comment by pokidovea** [comment]
I've cleaned up the code according to your idea. Please check the behaviour in master. If all's ok, I'll publish a new version.

**Comment by daybarr** [comment]
This is great. Thank you. I've had a quick look at your commits in master and they all look good to me. The master branch is also working 100% on my project's unit tests where it replaces freezegun perfectly. So much faster!

I will have a go at updating the README for you. PR on the way later this evening / morning if I can manage it.

**Pull request merged**
